/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './*.html',
    './js/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#54e083',
        'on-tertiary': '#4b2800',
        'surface-variant': '#2e372e',
        'tertiary': '#ffdec4',
        'surface-container-highest': '#2e372e',
        'primary': '#75ff9e',
        'tertiary-container': '#ffba79',
        'background': '#131313',
        'on-primary-fixed': '#00210b',
        'surface-tint': '#00e475',
        'surface-container-high': '#232c24',
        'on-tertiary-fixed-variant': '#6a3c03',
        'on-surface': '#dbe5d9',
        'on-primary': '#003918',
        'on-secondary': '#003918',
        'on-primary-fixed-variant': '#005226',
        'inverse-on-surface': '#29332a',
        'on-background': '#dbe5d9',
        'on-tertiary-container': '#794810',
        'on-surface-variant': '#bacbb9',
        'surface-container-low': '#151e16',
        'primary-fixed': '#62ff96',
        'secondary-fixed': '#73fd9c',
        'outline': '#859585',
        'on-primary-container': '#00612e',
        'secondary': '#54e083',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'expense-red': '#FFB4AB',
        'on-tertiary-fixed': '#2d1600',
        'inverse-primary': '#006d35',
        'error-container': '#93000a',
        'warning-amber': '#FFD54F',
        'secondary-container': '#00ad57',
        'surface-container-lowest': '#081009',
        'outline-variant': '#3b4a3d',
        'primary-fixed-dim': '#00e475',
        'surface-dim': '#0d150e',
        'tertiary-fixed-dim': '#fdb878',
        'surface': '#1A1A1A',
        'on-secondary-fixed': '#00210c',
        'primary-container': '#00e676',
        'surface-container': '#19221a',
        'on-secondary-container': '#003717',
        'border-subtle': 'rgba(255, 255, 255, 0.05)',
        'surface-bright': '#323c33',
        'on-secondary-fixed-variant': '#005226',
        'tertiary-fixed': '#ffdcbf',
        'error': '#ffb4ab',
        'inverse-surface': '#dbe5d9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '3xl': '24px',
      },
      spacing: {
        'margin-page': '2rem',
        'gutter': '1.5rem',
        'card-padding': '1.5rem',
        'stack-gap': '1rem',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk'],
        'body-lg': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'data-label': ['JetBrains Mono'],
        'body-md': ['Hanken Grotesk'],
        'data-display': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'data-label': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'data-display': ['20px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
